services:
  db:
    profiles:
      - full
      - db
    image: postgres
    restart: unless-stopped
    # set shared memory limit when using docker-compose
    shm_size: 512mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres:/var/lib/postgresql
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  redis-stack:
    profiles:
      - full
      - redis
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"

volumes:
  postgres:
  postgres-data:
